ALTER TABLE entity
    ADD COLUMN IF NOT EXISTS armour_class INT NULL,
    ADD COLUMN IF NOT EXISTS attack_bonus INT NULL,
    ADD COLUMN IF NOT EXISTS damage_dice VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS hp_max INT NULL,
    ADD COLUMN IF NOT EXISTS kind VARCHAR(64) NULL;
